const mongoose = require("mongoose");

const ProductSchema = new mongoose.Schema({
    group:{
        type:mongoose.Schema.ObjectId,
        ref:"Group",
        required:true,
    },
    brand:{
        type:mongoose.Schema.ObjectId,
        ref:"Brand",
        required:true,
    },
    product_id:{
        type:String,
        required:true,
    },
    product_name:{
        type:String,
        required:true,
    },
    plyUnit:{
        type:Number,
        required:true,
        daefault:11,
    },
    laborPerFloor:{
        type:Number,
        required:true,
        default:0,
    },
    applicability:{
        type:Number,
        required:true,
        default:2,
    },
    loadingUnloadingPrice:{
        type:Number,
        required:true,
        default:0,
    },
    product_description:{
        type:String,
        required:true,
    },
    category:{
        type:mongoose.Schema.ObjectId,
        ref:"Category",
        required:true,
    },
    subcategory:{
        type:mongoose.Schema.ObjectId,
        ref:"Subcategory",
        required:true,
    },
    plyid:{
        type:String,
        required:true,
    },
    description:{
        color:{
            type:String,
            required:true,
        },
        thickness:{
            type:String,
            required:true,
        }
    },
    attrs:{
        imgs:[
            type=String,
            required=true
        ]
    },
    averageRating:{
        type:Number,
        required:true,
        default:0,
    },
    vars:{
        type:String,
    },
    randomInt:{
        type:Number,
        required:true,
    }
});

module.exports = mongoose.model("Product",ProductSchema);